package hxluaplayer;

@:native("Gu")
extern class Gu {
    public static var COLOR_BUFFER_BIT: Int;
    public static var PI: Float;
	public static var FALSE: Int;
	public static var TRUE: Int;
	public static var POINTS: Int;
	public static var LINES: Int;
	public static var LINE_STRIP: Int;
	public static var TRIANGLES: Int;
	public static var TRIANGLE_STRIP: Int;
	public static var TRIANGLE_FAN: Int;
	public static var SPRITES: Int;
	public static var ALPHA_TEST: Int;
	public static var DEPTH_TEST: Int;
	public static var SCISSOR_TEST: Int;
	public static var STENCIL_TEST: Int;
	public static var BLEND: Int;
	public static var CULL_FACE: Int;
	public static var DITHER: Int;
	public static var FOG: Int;
	public static var CLIP_PLANES: Int;
	public static var TEXTURE_2D: Int;
	public static var LIGHTING: Int;
	public static var LIGHT0: Int;
	public static var LIGHT1: Int;
	public static var LIGHT2: Int;
	public static var LIGHT3: Int;
	public static var LINE_SMOOTH: Int;
	public static var PATCH_CULL_FACE: Int;
	public static var COLOR_TEST: Int;
	public static var COLOR_LOGIC_OP: Int;
	public static var FACE_NORMAL_REVERSE: Int;
	public static var PATCH_FACE: Int;
	public static var FRAGMENT_2X: Int;
	public static var PROJECTION: Int;
	public static var VIEW: Int;
	public static var MODEL: Int;
	public static var TEXTURE: Int;
	public static var TEXTURE_8BIT: Int;
	public static var TEXTURE_16BIT: Int;
	public static var TEXTURE_32BITF: Int;
	public static var TEXTURE_BITS: Int;
	public static var COLOR_RES1: Int;
	public static var COLOR_RES2: Int;
	public static var COLOR_RES3: Int;
	public static var COLOR_5650: Int;
	public static var COLOR_5551: Int;
	public static var COLOR_4444: Int;
	public static var COLOR_8888: Int;
	public static var COLOR_BITS: Int;
	public static var NORMAL_8BIT: Int;
	public static var NORMAL_16BIT: Int;
	public static var NORMAL_32BITF: Int;
	public static var NORMAL_BITS: Int;
	public static var VERTEX_8BIT: Int;
	public static var VERTEX_16BIT: Int;
	public static var VERTEX_32BITF: Int;
	public static var VERTEX_BITS: Int;
	public static var WEIGHT_8BIT: Int;
	public static var WEIGHT_16BIT: Int;
	public static var WEIGHT_32BITF: Int;
	public static var WEIGHT_BITS: Int;
	public static var INDEX_8BIT: Int;
	public static var INDEX_16BIT: Int;
	public static var INDEX_BITS: Int;
	public static var WEIGHTS_BITS: Int;
	public static var VERTICES_BITS: Int;
	public static var TRANSFORM_3D: Int;
	public static var TRANSFORM_2D: Int;
	public static var TRANSFORM_BITS: Int;
	public static var PSM_5650: Int;
	public static var PSM_5551: Int;
	public static var PSM_4444: Int;
	public static var PSM_8888: Int;
	public static var PSM_T4: Int;
	public static var PSM_T8: Int;
	public static var PSM_T16: Int;
	public static var PSM_T32: Int;
	public static var FLAT: Int;
	public static var SMOOTH: Int;
	public static var CLEAR: Int;
	public static var AND: Int;
	public static var AND_REVERSE: Int;
	public static var COPY: Int;
	public static var AND_INVERTED: Int;
	public static var NOOP: Int;
	public static var XOR: Int;
	public static var OR: Int;
	public static var NOR: Int;
	public static var EQUIV: Int;
	public static var INVERTED: Int;
	public static var OR_REVERSE: Int;
	public static var COPY_INVERTED: Int;
	public static var OR_INVERTED: Int;
	public static var NAND: Int;
	public static var SET: Int;
	public static var NEAREST: Int;
	public static var LINEAR: Int;
	public static var NEAREST_MIPMAP_NEAREST: Int;
	public static var LINEAR_MIPMAP_NEAREST: Int;
	public static var NEAREST_MIPMAP_LINEAR: Int;
	public static var LINEAR_MIPMAP_LINEAR: Int;
	public static var TEXTURE_COORDS: Int;
	public static var TEXTURE_MATRIX: Int;
	public static var ENVIRONMENT_MAP: Int;
	public static var POSITION: Int;
	public static var UV: Int;
	public static var NORMALIZED_NORMAL: Int;
	public static var NORMAL: Int;
	public static var REPEAT: Int;
	public static var CLAMP: Int;
	public static var CW: Int;
	public static var CCW: Int;
	public static var NEVER: Int;
	public static var ALWAYS: Int;
	public static var EQUAL: Int;
	public static var NOTEQUAL: Int;
	public static var LESS: Int;
	public static var LEQUAL: Int;
	public static var GREATER: Int;
	public static var GEQUAL: Int;
	public static var COLOR_BUFFER_BIT: Int;
	public static var STENCIL_BUFFER_BIT: Int;
	public static var DEPTH_BUFFER_BIT: Int;
	public static var TFX_MODULATE: Int;
	public static var TFX_DECAL: Int;
	public static var TFX_BLEND: Int;
	public static var TFX_REPLACE: Int;
	public static var TFX_ADD: Int;
	public static var TCC_RGB: Int;
	public static var TCC_RGBA: Int;
	public static var ADD: Int;
	public static var SUBTRACT: Int;
	public static var REVERSE_SUBTRACT: Int;
	public static var MIN: Int;
	public static var MAX: Int;
	public static var ABS: Int;
	public static var SRC_COLOR: Int;
	public static var ONE_MINUS_SRC_COLOR: Int;
	public static var SRC_ALPHA: Int;
	public static var ONE_MINUS_SRC_ALPHA: Int;
	public static var DST_COLOR: Int;
	public static var ONE_MINUS_DST_COLOR: Int;
	public static var DST_ALPHA: Int;
	public static var ONE_MINUS_DST_ALPHA: Int;
	public static var FIX: Int;
	public static var KEEP: Int;
	public static var ZERO: Int;
	public static var REPLACE: Int;
	public static var INVERT: Int;
	public static var INCR: Int;
	public static var DECR: Int;
	public static var AMBIENT: Int;
	public static var DIFFUSE: Int;
	public static var SPECULAR: Int;
	public static var AMBIENT_AND_DIFFUSE: Int;
	public static var DIFFUSE_AND_SPECULAR: Int;
	public static var UNKNOWN_LIGHT_COMPONENT: Int;
	public static var DIRECTIONAL: Int;
	public static var POINTLIGHT: Int;
	public static var SPOTLIGHT: Int;
	public static var DIRECT: Int;
	public static var CALL: Int;
	public static var SEND: Int;
	public static var TAIL: Int;
	public static var HEAD: Int;
    
    public static function clearColor(r: Float, g: Float, b: Float, a: Float): Void;
    public static function clearDepth(depth: Float): Void;
    public static function clear(state: Int): Void;
    public static function texImage(image: Image): Void;
    public static function texFunc(x: Int, y: Int): Void;
    public static function texEnvColor(color: Color): Void;
    public static function texFilter(min: Int, max: Int): Void;
    public static function texScale(sx: Float, sy: Float): Void;
    public static function texOffset(x: Float, y: Float): Void;
    public static function ambientColor(color: Color): Void;
    public static function ambient(color: Color): Void;
    public static function enable(cap: Int): Void;
    public static function disable(cap: Int): Void;
    public static function blendFunc(a: Int, b: Int, c: Int, d: Int, e: Int): Void;
    public static function light(r: Int, g: Int, b: Int, x: Float, y: Float, z: Float): Void;
    public static function lightAtt(a: Int, b: Int, c: Int, d: Int): Void;
    public static function lightColor(x: Int, y: Int, color: Color): Void;
    public static function lightMode(mode: Int): Void;
    public static function lightSpot(r: Int, g: Int, b: Int, x: Float, y: Float, z: Float): Void;
    public static function start3d(): Void;
    public static function end3d(): Void;
}
